#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 11 18:20:38 2019

@author: allisondavis
"""
#function that generates fibonacci sequence based on starting two numbers 
#f0 and f1 the length of the sequence is n.
def fib(f0,f1,n):
    fib=[f0,f1]
    for i in range(n-2):
        fib.append(fib[-1]+fib[-2]) 
    return fib

#%%creating an example sequence
fib(1,2,12)
#%% Does it satisfy Catalan's identity?
f_0=1 
f_1=1 #starting two numbers for the identity must be 1
j=6
k=2 #k must be less than j

if (fib(f_0,f_1,j)[-1]**2)-((fib(f_0,f_1,j+k)[-1])*(fib(f_0,f_1,j-k)[-1]))==((-1)**(j-k))*(fib(f_0,f_1,k)[-1]**2):
    print('true')
else:
    print('false')
    
#it works when the starting two terms are the same number but it does not hold
#when one is bigger than the other. It even works when they are the same
#negative number.
    
#%% Print out the last 10 terms of a sequence that you generated
print(fib(0,1,30)[-10:])

#last ten terms of the sequence starting with 0 and 1 going up to the 30th term.













